stages:
  train:
    cmd: python src/train.py --data_dir ${data_dir} --epochs ${epochs} --batch_size ${batch_size} --lr ${learning_rate}
    deps:
      - data/Cat
      - data/Dog
      - src/train.py
      - src/data_loader.py
    params:
      - epochs
      - batch_size
      - learning_rate
      - data_dir
    outs:
      - models/model.pt

  evaluate:
    cmd: python src/evaluate.py --model_path models/model.pt --data_dir ${data_dir}
    deps:
      - models/model.pt
      - src/evaluate.py
    metrics:
      - metrics.json:
          cache: false
